name: ellipsis_overflow_text
description: Flutter widget that automatically sets the number of lines to be shown on a text with the Ellipsis text overflow type.
version: 0.0.1
homepage: https://github.com/reiko-dev/ellipsis_overflow_text
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0