name: ellipsis_overflow_text
description: Flutter widget that automatically sets the number of lines to be shown on a text with the Ellipsis text overflow type.
version: 1.0.3
homepage: https://github.com/reiko-dev/ellipsis_overflow_text

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2